Scrapping Bloomberg Survelliance Transcripts

In [1]:
from headline_scrapper import Scraper

In [3]:
URL = "https://www.youtube.com/playlist?list=PLGaYlBJIOoa-qaI1saEniG3cR9V0Mu-PE"

url_lst_file_path = "./headline_scrapper/url_lst.txt" 
last_scrapped_index_file = "./headline_scrapper/start_index.txt"

with Scraper(URL) as scraper:
    scraper.Resume_Scrape(url_lst_file_path, last_scrapped_index_file)

INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1087
INFO: Extracted 1087 segments.
INFO: Transcripts Scrapped: 117/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1087
INFO: Extracted 1086 segments.
INFO: Transcripts Scrapped: 118/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1087
INFO: Extracted 1087 segments.
INFO: Transcripts Scrapped: 119/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1115
INFO: Extracted 1115 segments.
INFO: Transcripts Scrapped: 120/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1086
INFO: Extracted 1086 segments.
INFO: Transcripts Scrapped: 121/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1030
INFO: Extracted 1029 segments.
INFO: Transcripts Scrapped: 122/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1110
INFO: Extracted 1110 segments.
INFO: Transcripts Scrapped: 123/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1092
INFO: Extracted 1092 segments.
INFO: Transcripts Scrapped: 124/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1102
INFO: Extracted 1102 segments.
INFO: Transcripts Scrapped: 125/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 956
INFO: Extracted 956 segments.
INFO: Transcripts Scrapped: 126/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1128
INFO: Extracted 1127 segments.
INFO: Transcripts Scrapped: 127/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1052
INFO: Extracted 1051 segments.
INFO: Transcripts Scrapped: 128/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1079
INFO: Extracted 1078 segments.
INFO: Transcripts Scrapped: 129/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1034
INFO: Extracted 1034 segments.
INFO: Transcripts Scrapped: 130/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1007
INFO: Extracted 1007 segments.
INFO: Transcripts Scrapped: 131/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1086
INFO: Extracted 1086 segments.
INFO: Transcripts Scrapped: 132/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1059
INFO: Extracted 1058 segments.
INFO: Transcripts Scrapped: 133/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1350
INFO: Extracted 1350 segments.
INFO: Transcripts Scrapped: 134/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1132
INFO: Extracted 1132 segments.
INFO: Transcripts Scrapped: 135/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1089
INFO: Extracted 1089 segments.
INFO: Transcripts Scrapped: 136/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1063
INFO: Extracted 1063 segments.
INFO: Transcripts Scrapped: 137/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1063
INFO: Extracted 1063 segments.
INFO: Transcripts Scrapped: 138/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1090
INFO: Extracted 1090 segments.
INFO: Transcripts Scrapped: 139/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1081
INFO: Extracted 1081 segments.
INFO: Transcripts Scrapped: 140/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1067
INFO: Extracted 1067 segments.
INFO: Transcripts Scrapped: 141/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1102
INFO: Extracted 1102 segments.
INFO: Transcripts Scrapped: 142/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1111
INFO: Extracted 1111 segments.
INFO: Transcripts Scrapped: 143/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1197
INFO: Extracted 1196 segments.
INFO: Transcripts Scrapped: 144/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1070
INFO: Extracted 1070 segments.
INFO: Transcripts Scrapped: 145/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1103
INFO: Extracted 1103 segments.
INFO: Transcripts Scrapped: 146/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1090
INFO: Extracted 1090 segments.
INFO: Transcripts Scrapped: 147/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1070
INFO: Extracted 1069 segments.
INFO: Transcripts Scrapped: 148/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1065
INFO: Extracted 1065 segments.
INFO: Transcripts Scrapped: 149/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1078
INFO: Extracted 1077 segments.
INFO: Transcripts Scrapped: 150/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1082
INFO: Extracted 1082 segments.
INFO: Transcripts Scrapped: 151/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1104
INFO: Extracted 1103 segments.
INFO: Transcripts Scrapped: 152/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1073
INFO: Extracted 1073 segments.
INFO: Transcripts Scrapped: 153/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1108
INFO: Extracted 1108 segments.
INFO: Transcripts Scrapped: 154/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1056
INFO: Extracted 1056 segments.
INFO: Transcripts Scrapped: 155/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1091
INFO: Extracted 1091 segments.
INFO: Transcripts Scrapped: 156/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1089
INFO: Extracted 1089 segments.
INFO: Transcripts Scrapped: 157/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1068
INFO: Extracted 1068 segments.
INFO: Transcripts Scrapped: 158/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1079
INFO: Extracted 1079 segments.
INFO: Transcripts Scrapped: 159/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1121
INFO: Extracted 1121 segments.
INFO: Transcripts Scrapped: 160/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1079
INFO: Extracted 1079 segments.
INFO: Transcripts Scrapped: 161/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1088
INFO: Extracted 1088 segments.
INFO: Transcripts Scrapped: 162/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1088
INFO: Extracted 1088 segments.
INFO: Transcripts Scrapped: 163/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1103
INFO: Extracted 1103 segments.
INFO: Transcripts Scrapped: 164/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1063
INFO: Extracted 1063 segments.
INFO: Transcripts Scrapped: 165/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1021
INFO: Extracted 1021 segments.
INFO: Transcripts Scrapped: 166/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1129
INFO: Extracted 1129 segments.
INFO: Transcripts Scrapped: 167/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1090
INFO: Extracted 1090 segments.
INFO: Transcripts Scrapped: 168/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1063
INFO: Extracted 1063 segments.
INFO: Transcripts Scrapped: 169/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1079
INFO: Extracted 1079 segments.
INFO: Transcripts Scrapped: 170/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1093
INFO: Extracted 1093 segments.
INFO: Transcripts Scrapped: 171/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1063
INFO: Extracted 1063 segments.
INFO: Transcripts Scrapped: 172/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1072
INFO: Extracted 1072 segments.
INFO: Transcripts Scrapped: 173/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1095
INFO: Extracted 1095 segments.
INFO: Transcripts Scrapped: 174/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1102
INFO: Extracted 1102 segments.
INFO: Transcripts Scrapped: 175/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1112
INFO: Extracted 1112 segments.
INFO: Transcripts Scrapped: 176/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1078
INFO: Extracted 1078 segments.
INFO: Transcripts Scrapped: 177/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1062
INFO: Extracted 1062 segments.
INFO: Transcripts Scrapped: 178/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1113
INFO: Extracted 1113 segments.
INFO: Transcripts Scrapped: 179/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1084
INFO: Extracted 1084 segments.
INFO: Transcripts Scrapped: 180/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1085
INFO: Extracted 1085 segments.
INFO: Transcripts Scrapped: 181/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1052
INFO: Extracted 1052 segments.
INFO: Transcripts Scrapped: 182/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1107
INFO: Extracted 1107 segments.
INFO: Transcripts Scrapped: 183/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1101
INFO: Extracted 1101 segments.
INFO: Transcripts Scrapped: 184/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1082
INFO: Extracted 1082 segments.
INFO: Transcripts Scrapped: 185/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1085
INFO: Extracted 1085 segments.
INFO: Transcripts Scrapped: 186/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1057
INFO: Extracted 1057 segments.
INFO: Transcripts Scrapped: 187/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1080
INFO: Extracted 1080 segments.
INFO: Transcripts Scrapped: 188/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1100
INFO: Extracted 1100 segments.
INFO: Transcripts Scrapped: 189/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1076
INFO: Extracted 1076 segments.
INFO: Transcripts Scrapped: 190/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1080
INFO: Extracted 1080 segments.
INFO: Transcripts Scrapped: 191/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1065
INFO: Extracted 1065 segments.
INFO: Transcripts Scrapped: 192/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 698
INFO: Extracted 698 segments.
INFO: Transcripts Scrapped: 193/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1070
INFO: Extracted 1070 segments.
INFO: Transcripts Scrapped: 194/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1050
INFO: Extracted 1050 segments.
INFO: Transcripts Scrapped: 195/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1071
INFO: Extracted 1071 segments.
INFO: Transcripts Scrapped: 196/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1049
INFO: Extracted 1049 segments.
INFO: Transcripts Scrapped: 197/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1015
INFO: Extracted 1015 segments.
INFO: Transcripts Scrapped: 198/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1056
INFO: Extracted 1056 segments.
INFO: Transcripts Scrapped: 199/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1059
INFO: Extracted 1059 segments.
INFO: Transcripts Scrapped: 200/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1057
INFO: Extracted 1056 segments.
INFO: Transcripts Scrapped: 201/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 679
INFO: Extracted 679 segments.
INFO: Transcripts Scrapped: 202/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1058
INFO: Extracted 1058 segments.
INFO: Transcripts Scrapped: 203/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1072
INFO: Extracted 1072 segments.
INFO: Transcripts Scrapped: 204/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1060
INFO: Extracted 1060 segments.
INFO: Transcripts Scrapped: 205/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1046
INFO: Extracted 1046 segments.
INFO: Transcripts Scrapped: 206/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1088
INFO: Extracted 1088 segments.
INFO: Transcripts Scrapped: 207/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1063
INFO: Extracted 1063 segments.
INFO: Transcripts Scrapped: 208/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1068
INFO: Extracted 1068 segments.
INFO: Transcripts Scrapped: 209/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1072
INFO: Extracted 1072 segments.
INFO: Transcripts Scrapped: 210/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1049
INFO: Extracted 1049 segments.
INFO: Transcripts Scrapped: 211/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1124
INFO: Extracted 1124 segments.
INFO: Transcripts Scrapped: 212/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1047
INFO: Extracted 1047 segments.
INFO: Transcripts Scrapped: 213/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1047
INFO: Extracted 1047 segments.
INFO: Transcripts Scrapped: 214/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1079
INFO: Extracted 1079 segments.
INFO: Transcripts Scrapped: 215/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1041
INFO: Extracted 1041 segments.
INFO: Transcripts Scrapped: 216/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1077
INFO: Extracted 1077 segments.
INFO: Transcripts Scrapped: 217/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1007
INFO: Extracted 1007 segments.
INFO: Transcripts Scrapped: 218/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1074
INFO: Extracted 1074 segments.
INFO: Transcripts Scrapped: 219/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1043
INFO: Extracted 1043 segments.
INFO: Transcripts Scrapped: 220/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1063
INFO: Extracted 1063 segments.
INFO: Transcripts Scrapped: 221/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1079
INFO: Extracted 1079 segments.
INFO: Transcripts Scrapped: 222/550
INFO: Expanded video description.
INFO: Transcript panel opened.
INFO: Scrolling complete. Total segments in DOM: 1042
INFO: Extracted 1042 segments.
INFO: Transcripts Scrapped: 223/550
INFO: Expanded video description.
INFO: Transcript panel opened.

In [ ]:
#Next step step up a process to get date of transcript
#Set up a way to get all videos from date A to B

Getting sentiment scores by economic sector

In [1]:
from sentiment_analysis import SentimentAgent

In [2]:
agent = SentimentAgent()

folder_path = ".\Scrapped_Bloomberg_Transcripts"
agent.ConductSentimentAnalysis(folder_path, starting_index=0)

INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 1/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 2/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 3/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 4/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 5/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 6/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 7/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 8/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 9/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 10/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 11/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 12/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 13/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 14/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 15/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 16/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 17/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 18/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 19/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 20/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 21/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 22/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 23/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 24/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 25/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 26/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 27/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 28/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 29/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 30/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 31/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 32/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 33/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 34/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 35/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 36/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 37/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 38/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 39/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 40/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 41/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 42/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 43/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 44/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 45/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 46/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 47/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 48/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 49/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 50/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 51/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 52/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 53/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 54/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 55/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 56/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 57/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 58/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 59/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 60/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 61/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 62/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 63/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 64/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 65/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 66/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 67/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 68/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 69/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 70/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 71/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 72/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 73/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 74/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 75/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 76/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 77/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 78/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 79/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 80/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 81/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 82/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 83/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 84/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 85/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 86/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 87/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 88/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 89/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 90/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 91/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 92/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 93/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 94/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 95/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 96/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 97/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 98/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 99/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 100/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 101/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 102/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 103/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 104/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 105/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 106/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 107/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 108/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 109/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 110/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 111/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 112/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 113/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 114/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 115/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 116/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 117/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 118/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 119/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 120/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 121/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 122/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 123/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 124/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 125/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 126/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 127/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 128/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 129/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 130/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 131/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 132/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 133/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 134/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 135/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 136/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 137/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 138/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 139/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 140/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 141/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 142/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 143/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 144/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 145/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 146/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 147/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 148/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 149/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 150/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 151/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 152/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 153/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 154/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 155/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 156/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 157/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 158/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 159/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 160/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 161/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 162/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 163/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 164/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 165/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 166/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 167/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 168/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 169/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 170/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 171/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 172/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 173/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 174/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 175/547
INFO: HTTP Request: POST https://api.openai.com/v1/responses "HTTP/1.1 200 OK"
INFO: Transcript Analyzed: 176/547

Data Cleaning

In [1]:
#Data Cleaning
import pandas as pd
import json

df = pd.read_csv("./sentiment_analysis/Bloomberg_Transcript_Result.csv")

df["LLM Response"] = df["LLM Response"].apply(json.loads)

df

           Date                                       LLM Response
0    11_05_2024  {'Communication Services': 0.12, 'Consumer Dis...
1    02_02_2024  {'communication_services': 0.82, 'consumer_dis...
2       MISSING  {'Consumer Discretionary': 0.12, 'Consumer Sta...
3    07_09_2024  {'Communication Services': 0.2, 'Consumer Disc...
4    10_16_2024  {'communication_services': 0.05, 'consumer_dis...
..          ...                                                ...
542  11_06_2024  {'Communication Services': 0.1, 'Consumer Disc...
543  01_10_2025  {'Communication Services': 0.15, 'Consumer Dis...
544  02_07_2025  {'CommunicationServices': 0.3, 'ConsumerDiscre...
545  06_20_2024  {'Communication Services': 0.32, 'Consumer Dis...
546  02_07_2024  {'Financials': 0.05, 'Health Care': 0.0, 'Info...

[547 rows x 2 columns]

In [2]:
sector_map = {
    "Information Technology": [
        "Information Technology", "information_technology", "InformationTechnology",
        "Information_Technology", "Technology", "S&P 500 Information Technology", "XLK"
    ],
    "Health Care": [
        "Health Care", "health_care", "HealthCare", "Health_Care",
        "Healthcare", "S&P 500 Health Care", "XLV"
    ],
    "Financials": [
        "Financials", "financials", "Financial",
        "S&P 500 Financials", "XLF"
    ],
    "Consumer Discretionary": [
        "Consumer Discretionary", "consumer_discretionary", "ConsumerDiscretionary",
        "Consumer_Discretionary", "Consumer Cyclical",
        "S&P 500 Consumer Discretionary", "XLY"
    ],
    "Communication Services": [
        "Communication Services", "communication_services", "CommunicationServices",
        "Communication_Services", "Communication_services",
        "S&P 500 Communication Services", "XLC"
    ],
    "Industrials": [
        "Industrials", "industrials",
        "S&P 500 Industrials", "XLI"
    ],
    "Consumer Staples": [
        "Consumer Staples", "consumer_staples", "ConsumerStaples",
        "Consumer_Staples", "Consumer Defensive",
        "S&P 500 Consumer Staples", "XLP"
    ],
    "Energy": [
        "Energy", "energy",
        "S&P 500 Energy", "XLE"
    ],
    "Utilities": [
        "Utilities", "utilities",
        "S&P 500 Utilities", "XLU"
    ],
    "Real Estate": [
        "Real Estate", "real_estate", "RealEstate",
        "Real_Estate", "Real_estate",
        "S&P 500 Real Estate", "XLRE"
    ],
    "Materials": [
        "Materials", "materials", "Basic Materials", "BasicMaterials",
        "S&P 500 Materials", "XLB"
    ]
}

In [3]:
new_col = []

for data_dict in df["LLM Response"]:
    new_dict = {
        "Information Technology" : None,
        "Health Care": None,
        "Financials": None,
        "Consumer Discretionary": None,
        "Communication Services": None,
        "Industrials": None,
        "Consumer Staples" : None,
        "Energy" : None,
        "Utilities" : None,
        "Real Estate": None,
        "Materials" : None,
    }
    for key0 in new_dict:
        for key in data_dict:
            if key in sector_map[key0]:
                new_dict[key0] = data_dict[key]
                break
    new_col.append(new_dict)

In [4]:
new_col

[{'Information Technology': 0.2,
  'Health Care': 0.01,
  'Financials': 0.05,
  'Consumer Discretionary': 0.18,
  'Communication Services': 0.12,
  'Industrials': 0.09,
  'Consumer Staples': 0.02,
  'Energy': 0.08,
  'Utilities': 0.0,
  'Real Estate': -0.03,
  'Materials': 0.04},
 {'Information Technology': 0.74,
  'Health Care': 0.08,
  'Financials': 0.12,
  'Consumer Discretionary': 0.68,
  'Communication Services': 0.82,
  'Industrials': 0.41,
  'Consumer Staples': 0.05,
  'Energy': 0.18,
  'Utilities': -0.08,
  'Real Estate': -0.35,
  'Materials': 0.2},
 {'Information Technology': 0.61,
  'Health Care': 0.05,
  'Financials': 0.08,
  'Consumer Discretionary': 0.12,
  'Communication Services': 0.22,
  'Industrials': 0.74,
  'Consumer Staples': 0.02,
  'Energy': 0.78,
  'Utilities': 0.57,
  'Real Estate': 0.18,
  'Materials': 0.33},
 {'Information Technology': 0.3,
  'Health Care': -0.15,
  'Financials': 0.05,
  'Consumer Discretionary': 0.15,
  'Communication Services': 0.2,
  'Industrials': -0.1,
  'Consumer Staples': -0.35,
  'Energy': 0.1,
  'Utilities': 0.1,
  'Real Estate': -0.25,
  'Materials': -0.05},
 {'Information Technology': 0.1,
  'Health Care': -0.1,
  'Financials': 0.45,
  'Consumer Discretionary': 0.15,
  'Communication Services': 0.05,
  'Industrials': 0.0,
  'Consumer Staples': 0.1,
  'Energy': 0.2,
  'Utilities': 0.05,
  'Real Estate': 0.0,
  'Materials': -0.25},
 {'Information Technology': 0.1,
  'Health Care': 0.0,
  'Financials': 0.65,
  'Consumer Discretionary': 0.15,
  'Communication Services': 0.05,
  'Industrials': 0.25,
  'Consumer Staples': 0.1,
  'Energy': -0.05,
  'Utilities': -0.05,
  'Real Estate': 0.1,
  'Materials': 0.0},
 {'Information Technology': 0.63,
  'Health Care': 0.12,
  'Financials': 0.28,
  'Consumer Discretionary': 0.42,
  'Communication Services': 0.36,
  'Industrials': 0.31,
  'Consumer Staples': 0.18,
  'Energy': 0.21,
  'Utilities': 0.25,
  'Real Estate': 0.17,
  'Materials': 0.08},
 {'Information Technology': 0.55,
  'Health Care': 0.0,
  'Financials': 0.1,
  'Consumer Discretionary': 0.15,
  'Communication Services': 0.25,
  'Industrials': 0.05,
  'Consumer Staples': 0.05,
  'Energy': -0.1,
  'Utilities': 0.0,
  'Real Estate': -0.25,
  'Materials': 0.35},
 {'Information Technology': 0.41,
  'Health Care': 0.28,
  'Financials': 0.35,
  'Consumer Discretionary': 0.15,
  'Communication Services': 0.32,
  'Industrials': 0.06,
  'Consumer Staples': 0.18,
  'Energy': 0.22,
  'Utilities': -0.03,
  'Real Estate': 0.02,
  'Materials': -0.08},
 {'Information Technology': 0.45,
  'Health Care': 0.0,
  'Financials': 0.2,
  'Consumer Discretionary': 0.15,
  'Communication Services': 0.35,
  'Industrials': 0.05,
  'Consumer Staples': 0.05,
  'Energy': 0.1,
  'Utilities': -0.05,
  'Real Estate': -0.05,
  'Materials': 0.1},
 {'Information Technology': 0.0,
  'Health Care': 0.45,
  'Financials': 0.55,
  'Consumer Discretionary': 0.05,
  'Communication Services': 0.15,
  'Industrials': 0.1,
  'Consumer Staples': 0.1,
  'Energy': 0.35,
  'Utilities': -0.05,
  'Real Estate': -0.1,
  'Materials': 0.3},
 {'Information Technology': -0.16,
  'Health Care': 0.05,
  'Financials': -0.22,
  'Consumer Discretionary': -0.18,
  'Communication Services': 0.12,
  'Industrials': -0.04,
  'Consumer Staples': 0.08,
  'Energy': 0.19,
  'Utilities': 0.03,
  'Real Estate': -0.14,
  'Materials': -0.06},
 {'Information Technology': -0.22,
  'Health Care': -0.25,
  'Financials': 0.28,
  'Consumer Discretionary': -0.35,
  'Communication Services': 0.15,
  'Industrials': -0.18,
  'Consumer Staples': -0.12,
  'Energy': 0.62,
  'Utilities': -0.08,
  'Real Estate': -0.34,
  'Materials': -0.05},
 {'Information Technology': 0.3,
  'Health Care': 0.2,
  'Financials': 0.25,
  'Consumer Discretionary': 0.1,
  'Communication Services': 0.05,
  'Industrials': 0.45,
  'Consumer Staples': -0.05,
  'Energy': 0.35,
  'Utilities': 0.05,
  'Real Estate': -0.2,
  'Materials': 0.15},
 {'Information Technology': 0.55,
  'Health Care': 0.05,
  'Financials': 0.72,
  'Consumer Discretionary': 0.35,
  'Communication Services': 0.1,
  'Industrials': 0.18,
  'Consumer Staples': 0.15,
  'Energy': 0.08,
  'Utilities': 0.02,
  'Real Estate': 0.12,
  'Materials': 0.2},
 {'Information Technology': 0.2,
  'Health Care': 0.1,
  'Financials': 0.45,
  'Consumer Discretionary': 0.35,
  'Communication Services': 0.25,
  'Industrials': 0.4,
  'Consumer Staples': 0.15,
  'Energy': 0.3,
  'Utilities': 0.1,
  'Real Estate': 0.05,
  'Materials': 0.3},
 {'Information Technology': 0.4,
  'Health Care': 0.1,
  'Financials': 0.55,
  'Consumer Discretionary': 0.15,
  'Communication Services': 0.05,
  'Industrials': 0.25,
  'Consumer Staples': 0.0,
  'Energy': 0.45,
  'Utilities': 0.05,
  'Real Estate': -0.1,
  'Materials': 0.2},
 {'Information Technology': 0.75,
  'Health Care': 0.45,
  'Financials': 0.25,
  'Consumer Discretionary': 0.4,
  'Communication Services': 0.5,
  'Industrials': 0.2,
  'Consumer Staples': 0.35,
  'Energy': 0.15,
  'Utilities': 0.1,
  'Real Estate': -0.05,
  'Materials': 0.1},
 {'Information Technology': 0.8,
  'Health Care': 0.1,
  'Financials': 0.7,
  'Consumer Discretionary': 0.55,
  'Communication Services': 0.8,
  'Industrials': 0.6,
  'Consumer Staples': 0.35,
  'Energy': 0.65,
  'Utilities': 0.2,
  'Real Estate': 0.15,
  'Materials': 0.25},
 {'Information Technology': 0.28,
  'Health Care': 0.14,
  'Financials': 0.22,
  'Consumer Discretionary': 0.12,
  'Communication Services': 0.05,
  'Industrials': 0.17,
  'Consumer Staples': 0.02,
  'Energy': 0.18,
  'Utilities': 0.06,
  'Real Estate': 0.1,
  'Materials': 0.16},
 {'Information Technology': 0.75,
  'Health Care': 0.55,
  'Financials': 0.65,
  'Consumer Discretionary': 0.7,
  'Communication Services': 0.85,
  'Industrials': 0.6,
  'Consumer Staples': 0.25,
  'Energy': 0.8,
  'Utilities': 0.4,
  'Real Estate': 0.45,
  'Materials': 0.35},
 {'Information Technology': 0.45,
  'Health Care': 0.22,
  'Financials': 0.33,
  'Consumer Discretionary': 0.32,
  'Communication Services': 0.44,
  'Industrials': 0.37,
  'Consumer Staples': 0.18,
  'Energy': 0.41,
  'Utilities': 0.29,
  'Real Estate': 0.17,
  'Materials': 0.24},
 {'Information Technology': 0.2,
  'Health Care': 0.08,
  'Financials': 0.18,
  'Consumer Discretionary': -0.08,
  'Communication Services': 0.12,
  'Industrials': -0.22,
  'Consumer Staples': 0.02,
  'Energy': 0.15,
  'Utilities': 0.04,
  'Real Estate': 0.05,
  'Materials': 0.03},
 {'Information Technology': -0.9,
  'Health Care': 0.05,
  'Financials': -0.1,
  'Consumer Discretionary': -0.05,
  'Communication Services': 0.1,
  'Industrials': 0.0,
  'Consumer Staples': 0.0,
  'Energy': -0.75,
  'Utilities': -0.7,
  'Real Estate': -0.05,
  'Materials': -0.15},
 {'Information Technology': 0.58,
  'Health Care': 0.04,
  'Financials': 0.08,
  'Consumer Discretionary': 0.18,
  'Communication Services': 0.42,
  'Industrials': -0.02,
  'Consumer Staples': 0.05,
  'Energy': 0.12,
  'Utilities': 0.03,
  'Real Estate': -0.12,
  'Materials': -0.06},
 {'Information Technology': 0.75,
  'Health Care': 0.3,
  'Financials': 0.15,
  'Consumer Discretionary': 0.2,
  'Communication Services': 0.55,
  'Industrials': 0.25,
  'Consumer Staples': 0.1,
  'Energy': -0.25,
  'Utilities': -0.3,
  'Real Estate': 0.05,
  'Materials': 0.45},
 {'Information Technology': 0.38,
  'Health Care': -0.05,
  'Financials': 0.05,
  'Consumer Discretionary': 0.18,
  'Communication Services': 0.45,
  'Industrials': -0.32,
  'Consumer Staples': -0.22,
  'Energy': -0.1,
  'Utilities': -0.08,
  'Real Estate': -0.06,
  'Materials': -0.28},
 {'Information Technology': -0.35,
  'Health Care': 0.05,
  'Financials': 0.05,
  'Consumer Discretionary': 0.05,
  'Communication Services': 0.1,
  'Industrials': -0.15,
  'Consumer Staples': 0.0,
  'Energy': 0.15,
  'Utilities': 0.0,
  'Real Estate': -0.05,
  'Materials': 0.0},
 {'Information Technology': 0.3,
  'Health Care': 0.0,
  'Financials': -0.05,
  'Consumer Discretionary': 0.15,
  'Communication Services': 0.25,
  'Industrials': -0.2,
  'Consumer Staples': 0.05,
  'Energy': -0.45,
  'Utilities': 0.05,
  'Real Estate': -0.1,
  'Materials': -0.15},
 {'Information Technology': 0.3,
  'Health Care': 0.0,
  'Financials': -0.35,
  'Consumer Discretionary': 0.2,
  'Communication Services': 0.15,
  'Industrials': -0.15,
  'Consumer Staples': 0.05,
  'Energy': 0.1,
  'Utilities': 0.0,
  'Real Estate': -0.5,
  'Materials': -0.1},
 {'Information Technology': 0.08,
  'Health Care': 0.1,
  'Financials': 0.02,
  'Consumer Discretionary': -0.25,
  'Communication Services': 0.15,
  'Industrials': -0.35,
  'Consumer Staples': 0.05,
  'Energy': -0.3,
  'Utilities': 0.02,
  'Real Estate': -0.05,
  'Materials': -0.4},
 {'Information Technology': None,
  'Health Care': None,
  'Financials': None,
  'Consumer Discretionary': None,
  'Communication Services': None,
  'Industrials': None,
  'Consumer Staples': None,
  'Energy': None,
  'Utilities': None,
  'Real Estate': None,
  'Materials': None},
 {'Information Technology': 0.25,
  'Health Care': 0.0,
  'Financials': 0.1,
  'Consumer Discretionary': 0.15,
  'Communication Services': 0.2,
  'Industrials': 0.35,
  'Consumer Staples': -0.1,
  'Energy': 0.55,
  'Utilities': -0.05,
  'Real Estate': -0.15,
  'Materials': 0.15},
 {'Information Technology': 0.1,
  'Health Care': 0.2,
  'Financials': 0.15,
  'Consumer Discretionary': 0.2,
  'Communication Services': 0.1,
  'Industrials': 0.05,
  'Consumer Staples': 0.05,
  'Energy': -0.05,
  'Utilities': 0.0,
  'Real Estate': 0.0,
  'Materials': -0.1},
 {'Information Technology': 0.46,
  'Health Care': 0.08,
  'Financials': 0.11,
  'Consumer Discretionary': 0.58,
  'Communication Services': 0.35,
  'Industrials': 0.14,
  'Consumer Staples': -0.06,
  'Energy': 0.22,
  'Utilities': 0.04,
  'Real Estate': 0.33,
  'Materials': 0.09},
 {'Information Technology': 0.25,
  'Health Care': 0.35,
  'Financials': 0.2,
  'Consumer Discretionary': 0.55,
  'Communication Services': 0.2,
  'Industrials': 0.1,
  'Consumer Staples': 0.15,
  'Energy': 0.05,
  'Utilities': 0.0,
  'Real Estate': -0.15,
  'Materials': 0.3},
 {'Information Technology': 0.2,
  'Health Care': 0.05,
  'Financials': 0.6,
  'Consumer Discretionary': 0.1,
  'Communication Services': 0.3,
  'Industrials': -0.35,
  'Consumer Staples': 0.15,
  'Energy': -0.05,
  'Utilities': 0.1,
  'Real Estate': 0.0,
  'Materials': -0.15},
 {'Information Technology': -0.05,
  'Health Care': -0.1,
  'Financials': 0.05,
  'Consumer Discretionary': -0.1,
  'Communication Services': 0.1,
  'Industrials': -0.4,
  'Consumer Staples': -0.05,
  'Energy': -0.15,
  'Utilities': 0.0,
  'Real Estate': -0.1,
  'Materials': -0.45},
 {'Information Technology': 0.25,
  'Health Care': 0.1,
  'Financials': -0.05,
  'Consumer Discretionary': 0.05,
  'Communication Services': 0.15,
  'Industrials': 0.12,
  'Consumer Staples': -0.1,
  'Energy': 0.2,
  'Utilities': 0.05,
  'Real Estate': 0.02,
  'Materials': 0.08},
 {'Information Technology': 0.45,
  'Health Care': 0.1,
  'Financials': 0.2,
  'Consumer Discretionary': 0.15,
  'Communication Services': 0.25,
  'Industrials': 0.15,
  'Consumer Staples': -0.2,
  'Energy': 0.35,
  'Utilities': -0.1,
  'Real Estate': -0.35,
  'Materials': 0.3},
 {'Information Technology': 0.15,
  'Health Care': 0.05,
  'Financials': 0.35,
  'Consumer Discretionary': -0.1,
  'Communication Services': 0.1,
  'Industrials': -0.25,
  'Consumer Staples': -0.05,
  'Energy': -0.15,
  'Utilities': -0.05,
  'Real Estate': -0.2,
  'Materials': -0.2},
 {'Information Technology': 0.1,
  'Health Care': -0.05,
  'Financials': -0.1,
  'Consumer Discretionary': -0.15,
  'Communication Services': 0.05,
  'Industrials': -0.2,
  'Consumer Staples': -0.2,
  'Energy': -0.25,
  'Utilities': -0.05,
  'Real Estate': -0.1,
  'Materials': -0.15},
 {'Information Technology': 0.61,
  'Health Care': 0.22,
  'Financials': 0.3,
  'Consumer Discretionary': 0.58,
  'Communication Services': 0.72,
  'Industrials': 0.14,
  'Consumer Staples': 0.18,
  'Energy': 0.12,
  'Utilities': 0.02,
  'Real Estate': -0.05,
  'Materials': 0.08},
 {'Information Technology': 0.15,
  'Health Care': 0.0,
  'Financials': 0.05,
  'Consumer Discretionary': 0.25,
  'Communication Services': 0.12,
  'Industrials': 0.2,
  'Consumer Staples': 0.1,
  'Energy': -0.05,
  'Utilities': -0.02,
  'Real Estate': 0.0,
  'Materials': 0.05},
 {'Information Technology': 0.75,
  'Health Care': 0.15,
  'Financials': 0.25,
  'Consumer Discretionary': 0.2,
  'Communication Services': 0.55,
  'Industrials': -0.25,
  'Consumer Staples': -0.1,
  'Energy': -0.2,
  'Utilities': 0.05,
  'Real Estate': 0.1,
  'Materials': -0.3},
 {'Information Technology': 0.2,
  'Health Care': 0.1,
  'Financials': 0.05,
  'Consumer Discretionary': 0.05,
  'Communication Services': 0.15,
  'Industrials': -0.05,
  'Consumer Staples': -0.1,
  'Energy': 0.35,
  'Utilities': 0.0,
  'Real Estate': -0.15,
  'Materials': 0.1},
 {'Information Technology': 0.35,
  'Health Care': 0.1,
  'Financials': 0.2,
  'Consumer Discretionary': 0.3,
  'Communication Services': 0.25,
  'Industrials': 0.2,
  'Consumer Staples': 0.15,
  'Energy': 0.05,
  'Utilities': 0.05,
  'Real Estate': 0.12,
  'Materials': 0.08},
 {'Information Technology': None,
  'Health Care': None,
  'Financials': None,
  'Consumer Discretionary': None,
  'Communication Services': None,
  'Industrials': None,
  'Consumer Staples': None,
  'Energy': None,
  'Utilities': None,
  'Real Estate': None,
  'Materials': None},
 {'Information Technology': 0.28,
  'Health Care': 0.0,
  'Financials': -0.12,
  'Consumer Discretionary': -0.18,
  'Communication Services': 0.05,
  'Industrials': -0.1,
  'Consumer Staples': 0.12,
  'Energy': 0.08,
  'Utilities': -0.02,
  'Real Estate': -0.22,
  'Materials': -0.05},
 {'Information Technology': 0.15,
  'Health Care': -0.25,
  'Financials': 0.1,
  'Consumer Discretionary': -0.35,
  'Communication Services': 0.05,
  'Industrials': -0.3,
  'Consumer Staples': -0.15,
  'Energy': -0.2,
  'Utilities': 0.05,
  'Real Estate': -0.1,
  'Materials': -0.35},
 {'Information Technology': 0.62,
  'Health Care': 0.12,
  'Financials': -0.08,
  'Consumer Discretionary': 0.21,
  'Communication Services': 0.16,
  'Industrials': 0.14,
  'Consumer Staples': 0.05,
  'Energy': 0.24,
  'Utilities': -0.02,
  'Real Estate': 0.17,
  'Materials': 0.03},
 {'Information Technology': 0.08,
  'Health Care': -0.3,
  'Financials': 0.15,
  'Consumer Discretionary': 0.05,
  'Communication Services': None,
  'Industrials': -0.05,
  'Consumer Staples': 0.1,
  'Energy': 0.0,
  'Utilities': 0.12,
  'Real Estate': -0.15,
  'Materials': 0.2},
 {'Information Technology': 0.95,
  'Health Care': 0.15,
  'Financials': 0.05,
  'Consumer Discretionary': 0.25,
  'Communication Services': 0.2,
  'Industrials': 0.35,
  'Consumer Staples': 0.05,
  'Energy': 0.1,
  'Utilities': 0.0,
  'Real Estate': -0.15,
  'Materials': 0.15},
 {'Information Technology': 0.86,
  'Health Care': 0.31,
  'Financials': 0.22,
  'Consumer Discretionary': 0.52,
  'Communication Services': 0.38,
  'Industrials': 0.44,
  'Consumer Staples': 0.18,
  'Energy': 0.05,
  'Utilities': 0.04,
  'Real Estate': 0.08,
  'Materials': 0.12},
 {'Information Technology': -0.45,
  'Health Care': -0.15,
  'Financials': 0.05,
  'Consumer Discretionary': -0.2,
  'Communication Services': 0.1,
  'Industrials': -0.25,
  'Consumer Staples': 0.05,
  'Energy': 0.15,
  'Utilities': 0.05,
  'Real Estate': -0.3,
  'Materials': -0.2},
 {'Information Technology': 0.34,
  'Health Care': 0.05,
  'Financials': -0.05,
  'Consumer Discretionary': -0.18,
  'Communication Services': 0.72,
  'Industrials': 0.02,
  'Consumer Staples': 0.08,
  'Energy': -0.12,
  'Utilities': 0.04,
  'Real Estate': -0.2,
  'Materials': -0.08},
 {'Information Technology': 0.2,
  'Health Care': -0.05,
  'Financials': 0.05,
  'Consumer Discretionary': 0.1,
  'Communication Services': 0.15,
  'Industrials': -0.15,
  'Consumer Staples': -0.05,
  'Energy': -0.1,
  'Utilities': 0.05,
  'Real Estate': -0.05,
  'Materials': -0.1},
 {'Information Technology': 0.72,
  'Health Care': 0.18,
  'Financials': 0.22,
  'Consumer Discretionary': -0.08,
  'Communication Services': 0.38,
  'Industrials': 0.16,
  'Consumer Staples': 0.12,
  'Energy': -0.18,
  'Utilities': -0.12,
  'Real Estate': -0.14,
  'Materials': -0.05},
 {'Information Technology': 0.15,
  'Health Care': 0.25,
  'Financials': 0.05,
  'Consumer Discretionary': -0.35,
  'Communication Services': -0.1,
  'Industrials': -0.05,
  'Consumer Staples': 0.1,
  'Energy': 0.2,
  'Utilities': 0.05,
  'Real Estate': -0.15,
  'Materials': -0.3},
 {'Information Technology': 0.05,
  'Health Care': 0.1,
  'Financials': 0.05,
  'Consumer Discretionary': 0.15,
  'Communication Services': 0.1,
  'Industrials': 0.0,
  'Consumer Staples': 0.05,
  'Energy': 0.0,
  'Utilities': 0.0,
  'Real Estate': -0.1,
  'Materials': -0.05},
 {'Information Technology': 0.2,
  'Health Care': 0.1,
  'Financials': -0.35,
  'Consumer Discretionary': 0.15,
  'Communication Services': 0.2,
  'Industrials': 0.05,
  'Consumer Staples': 0.1,
  'Energy': 0.25,
  'Utilities': 0.0,
  'Real Estate': -0.4,
  'Materials': 0.15},
 {'Information Technology': -0.05,
  'Health Care': 0.04,
  'Financials': 0.1,
  'Consumer Discretionary': -0.08,
  'Communication Services': 0.12,
  'Industrials': 0.18,
  'Consumer Staples': 0.05,
  'Energy': -0.18,
  'Utilities': -0.04,
  'Real Estate': -0.12,
  'Materials': 0.09},
 {'Information Technology': 0.22,
  'Health Care': 0.11,
  'Financials': 0.14,
  'Consumer Discretionary': 0.08,
  'Communication Services': 0.12,
  'Industrials': 0.18,
  'Consumer Staples': 0.02,
  'Energy': -0.03,
  'Utilities': 0.01,
  'Real Estate': 0.05,
  'Materials': 0.09},
 {'Information Technology': 0.02,
  'Health Care': 0.14,
  'Financials': 0.06,
  'Consumer Discretionary': 0.12,
  'Communication Services': 0.01,
  'Industrials': 0.05,
  'Consumer Staples': 0.18,
  'Energy': 0.08,
  'Utilities': -0.05,
  'Real Estate': -0.12,
  'Materials': 0.0},
 {'Information Technology': None,
  'Health Care': None,
  'Financials': None,
  'Consumer Discretionary': None,
  'Communication Services': None,
  'Industrials': None,
  'Consumer Staples': None,
  'Energy': None,
  'Utilities': None,
  'Real Estate': None,
  'Materials': None},
 {'Information Technology': 0.35,
  'Health Care': 0.15,
  'Financials': 0.45,
  'Consumer Discretionary': 0.55,
  'Communication Services': 0.2,
  'Industrials': 0.25,
  'Consumer Staples': 0.1,
  'Energy': 0.05,
  'Utilities': 0.0,
  'Real Estate': -0.2,
  'Materials': 0.05},
 {'Information Technology': -0.5,
  'Health Care': -0.1,
  'Financials': -0.7,
  'Consumer Discretionary': -0.55,
  'Communication Services': 0.1,
  'Industrials': -0.45,
  'Consumer Staples': -0.15,
  'Energy': -0.25,
  'Utilities': 0.05,
  'Real Estate': -0.2,
  'Materials': -0.35},
 {'Information Technology': 0.05,
  'Health Care': 0.0,
  'Financials': 0.1,
  'Consumer Discretionary': -0.05,
  'Communication Services': -0.2,
  'Industrials': -0.1,
  'Consumer Staples': 0.02,
  'Energy': 0.03,
  'Utilities': 0.08,
  'Real Estate': -0.15,
  'Materials': -0.05},
 {'Information Technology': -0.18,
  'Health Care': 0.22,
  'Financials': -0.41,
  'Consumer Discretionary': -0.72,
  'Communication Services': -0.22,
  'Industrials': -0.56,
  'Consumer Staples': 0.18,
  'Energy': -0.34,
  'Utilities': 0.11,
  'Real Estate': -0.12,
  'Materials': -0.63},
 {'Information Technology': -0.4,
  'Health Care': 0.0,
  'Financials': -0.15,
  'Consumer Discretionary': -0.35,
  'Communication Services': 0.05,
  'Industrials': -0.25,
  'Consumer Staples': -0.1,
  'Energy': 0.1,
  'Utilities': 0.02,
  'Real Estate': -0.05,
  'Materials': -0.45},
 {'Information Technology': 0.3,
  'Health Care': 0.15,
  'Financials': 0.25,
  'Consumer Discretionary': 0.45,
  'Communication Services': 0.35,
  'Industrials': 0.05,
  'Consumer Staples': 0.1,
  'Energy': 0.2,
  'Utilities': -0.05,
  'Real Estate': -0.15,

In [5]:
df["LLM Response"] = new_col

In [6]:
df["LLM Response"]

0      {'Information Technology': 0.2, 'Health Care':...
1      {'Information Technology': 0.74, 'Health Care'...
2      {'Information Technology': 0.61, 'Health Care'...
3      {'Information Technology': 0.3, 'Health Care':...
4      {'Information Technology': 0.1, 'Health Care':...
                             ...
542    {'Information Technology': 0.4, 'Health Care':...
543    {'Information Technology': 0.2, 'Health Care':...
544    {'Information Technology': 0.25, 'Health Care'...
545    {'Information Technology': 0.45, 'Health Care'...
546    {'Information Technology': 0.25, 'Health Care'...
Name: LLM Response, Length: 547, dtype: object

In [39]:
""" 
Some of the vals of the jsons arent floats their dictionaries, check how many of those types there
"""
correct_format_cnt = 0 #float vals
other_format_cnt = 0

incorrect_format_index = []

for index,row in enumerate(df["LLM Response"]):
    for key in row:
        if (type(row[key]) == float):
            correct_format_cnt +=1
        else:
            if (row[key] != None): 
                other_format_cnt+=1
                if index not in incorrect_format_index:
                    incorrect_format_index.append(index)

print(f"Correct Format Count: {correct_format_cnt}\nOther Format Count: {other_format_cnt}")

Correct Format Count: 5892
Other Format Count: 11

In [13]:
len(incorrect_format_index)

26

In [40]:
incorrect_format_index #Looks fine: 75 303

[493]

In [38]:
df.iloc[493,1]

{'Information Technology': 0,
 'Health Care': 0,
 'Financials': 0,
 'Consumer Discretionary': 0,
 'Communication Services': 0,
 'Industrials': 0,
 'Consumer Staples': 0,
 'Energy': 0,
 'Utilities': 0,
 'Real Estate': 0,
 'Materials': 0}

In [23]:
x["Communication Services"]["sentiment"]

0.4

In [33]:
for bad_index in incorrect_format_index:
    new_dict = {
        "Information Technology" : None,
        "Health Care": None,
        "Financials": None,
        "Consumer Discretionary": None,
        "Communication Services": None,
        "Industrials": None,
        "Consumer Staples" : None,
        "Energy" : None,
        "Utilities" : None,
        "Real Estate": None,
        "Materials" : None,
    }

    data = df.iloc[bad_index, 1]
    for key in data:
        try:
            val = data[key]["sentiment"]
        except:
            print(data)
        new_dict[key] = val
    
    #df.iat[bad_index,1] = new_dict

{'Information Technology': -0.28, 'Health Care': -0.12, 'Financials': -0.18, 'Consumer Discretionary': -0.72, 'Communication Services': -0.15, 'Industrials': -0.22, 'Consumer Staples': -0.34, 'Energy': 0.08, 'Utilities': 0.05, 'Real Estate': -0.31, 'Materials': -0.25}
{'Information Technology': -0.28, 'Health Care': -0.12, 'Financials': -0.18, 'Consumer Discretionary': -0.72, 'Communication Services': -0.15, 'Industrials': -0.22, 'Consumer Staples': -0.34, 'Energy': 0.08, 'Utilities': 0.05, 'Real Estate': -0.31, 'Materials': -0.25}
{'Information Technology': -0.28, 'Health Care': -0.12, 'Financials': -0.18, 'Consumer Discretionary': -0.72, 'Communication Services': -0.15, 'Industrials': -0.22, 'Consumer Staples': -0.34, 'Energy': 0.08, 'Utilities': 0.05, 'Real Estate': -0.31, 'Materials': -0.25}
{'Information Technology': -0.28, 'Health Care': -0.12, 'Financials': -0.18, 'Consumer Discretionary': -0.72, 'Communication Services': -0.15, 'Industrials': -0.22, 'Consumer Staples': -0.34, 'Energy': 0.08, 'Utilities': 0.05, 'Real Estate': -0.31, 'Materials': -0.25}
{'Information Technology': -0.28, 'Health Care': -0.12, 'Financials': -0.18, 'Consumer Discretionary': -0.72, 'Communication Services': -0.15, 'Industrials': -0.22, 'Consumer Staples': -0.34, 'Energy': 0.08, 'Utilities': 0.05, 'Real Estate': -0.31, 'Materials': -0.25}
{'Information Technology': -0.28, 'Health Care': -0.12, 'Financials': -0.18, 'Consumer Discretionary': -0.72, 'Communication Services': -0.15, 'Industrials': -0.22, 'Consumer Staples': -0.34, 'Energy': 0.08, 'Utilities': 0.05, 'Real Estate': -0.31, 'Materials': -0.25}
{'Information Technology': -0.28, 'Health Care': -0.12, 'Financials': -0.18, 'Consumer Discretionary': -0.72, 'Communication Services': -0.15, 'Industrials': -0.22, 'Consumer Staples': -0.34, 'Energy': 0.08, 'Utilities': 0.05, 'Real Estate': -0.31, 'Materials': -0.25}
{'Information Technology': -0.28, 'Health Care': -0.12, 'Financials': -0.18, 'Consumer Discretionary': -0.72, 'Communication Services': -0.15, 'Industrials': -0.22, 'Consumer Staples': -0.34, 'Energy': 0.08, 'Utilities': 0.05, 'Real Estate': -0.31, 'Materials': -0.25}
{'Information Technology': -0.28, 'Health Care': -0.12, 'Financials': -0.18, 'Consumer Discretionary': -0.72, 'Communication Services': -0.15, 'Industrials': -0.22, 'Consumer Staples': -0.34, 'Energy': 0.08, 'Utilities': 0.05, 'Real Estate': -0.31, 'Materials': -0.25}
{'Information Technology': -0.28, 'Health Care': -0.12, 'Financials': -0.18, 'Consumer Discretionary': -0.72, 'Communication Services': -0.15, 'Industrials': -0.22, 'Consumer Staples': -0.34, 'Energy': 0.08, 'Utilities': 0.05, 'Real Estate': -0.31, 'Materials': -0.25}
{'Information Technology': -0.28, 'Health Care': -0.12, 'Financials': -0.18, 'Consumer Discretionary': -0.72, 'Communication Services': -0.15, 'Industrials': -0.22, 'Consumer Staples': -0.34, 'Energy': 0.08, 'Utilities': 0.05, 'Real Estate': -0.31, 'Materials': -0.25}
{'Information Technology': 0.6, 'Health Care': -0.15, 'Financials': 0.2, 'Consumer Discretionary': 0.45, 'Communication Services': 0.4, 'Industrials': 0.25, 'Consumer Staples': 0.1, 'Energy': -0.05, 'Utilities': 0.05, 'Real Estate': 0.15, 'Materials': 0.05}
{'Information Technology': 0.6, 'Health Care': -0.15, 'Financials': 0.2, 'Consumer Discretionary': 0.45, 'Communication Services': 0.4, 'Industrials': 0.25, 'Consumer Staples': 0.1, 'Energy': -0.05, 'Utilities': 0.05, 'Real Estate': 0.15, 'Materials': 0.05}
{'Information Technology': 0.6, 'Health Care': -0.15, 'Financials': 0.2, 'Consumer Discretionary': 0.45, 'Communication Services': 0.4, 'Industrials': 0.25, 'Consumer Staples': 0.1, 'Energy': -0.05, 'Utilities': 0.05, 'Real Estate': 0.15, 'Materials': 0.05}
{'Information Technology': 0.6, 'Health Care': -0.15, 'Financials': 0.2, 'Consumer Discretionary': 0.45, 'Communication Services': 0.4, 'Industrials': 0.25, 'Consumer Staples': 0.1, 'Energy': -0.05, 'Utilities': 0.05, 'Real Estate': 0.15, 'Materials': 0.05}
{'Information Technology': 0.6, 'Health Care': -0.15, 'Financials': 0.2, 'Consumer Discretionary': 0.45, 'Communication Services': 0.4, 'Industrials': 0.25, 'Consumer Staples': 0.1, 'Energy': -0.05, 'Utilities': 0.05, 'Real Estate': 0.15, 'Materials': 0.05}
{'Information Technology': 0.6, 'Health Care': -0.15, 'Financials': 0.2, 'Consumer Discretionary': 0.45, 'Communication Services': 0.4, 'Industrials': 0.25, 'Consumer Staples': 0.1, 'Energy': -0.05, 'Utilities': 0.05, 'Real Estate': 0.15, 'Materials': 0.05}
{'Information Technology': 0.6, 'Health Care': -0.15, 'Financials': 0.2, 'Consumer Discretionary': 0.45, 'Communication Services': 0.4, 'Industrials': 0.25, 'Consumer Staples': 0.1, 'Energy': -0.05, 'Utilities': 0.05, 'Real Estate': 0.15, 'Materials': 0.05}
{'Information Technology': 0.6, 'Health Care': -0.15, 'Financials': 0.2, 'Consumer Discretionary': 0.45, 'Communication Services': 0.4, 'Industrials': 0.25, 'Consumer Staples': 0.1, 'Energy': -0.05, 'Utilities': 0.05, 'Real Estate': 0.15, 'Materials': 0.05}
{'Information Technology': 0.6, 'Health Care': -0.15, 'Financials': 0.2, 'Consumer Discretionary': 0.45, 'Communication Services': 0.4, 'Industrials': 0.25, 'Consumer Staples': 0.1, 'Energy': -0.05, 'Utilities': 0.05, 'Real Estate': 0.15, 'Materials': 0.05}
{'Information Technology': 0.6, 'Health Care': -0.15, 'Financials': 0.2, 'Consumer Discretionary': 0.45, 'Communication Services': 0.4, 'Industrials': 0.25, 'Consumer Staples': 0.1, 'Energy': -0.05, 'Utilities': 0.05, 'Real Estate': 0.15, 'Materials': 0.05}
{'Information Technology': 0.6, 'Health Care': -0.15, 'Financials': 0.2, 'Consumer Discretionary': 0.45, 'Communication Services': 0.4, 'Industrials': 0.25, 'Consumer Staples': 0.1, 'Energy': -0.05, 'Utilities': 0.05, 'Real Estate': 0.15, 'Materials': 0.05}
{'Information Technology': 0.12, 'Health Care': -0.28, 'Financials': -0.18, 'Consumer Discretionary': -0.2, 'Communication Services': 0.08, 'Industrials': -0.1, 'Consumer Staples': -0.05, 'Energy': 0.22, 'Utilities': -0.02, 'Real Estate': -0.22, 'Materials': -0.12}
{'Information Technology': 0.12, 'Health Care': -0.28, 'Financials': -0.18, 'Consumer Discretionary': -0.2, 'Communication Services': 0.08, 'Industrials': -0.1, 'Consumer Staples': -0.05, 'Energy': 0.22, 'Utilities': -0.02, 'Real Estate': -0.22, 'Materials': -0.12}
{'Information Technology': 0.12, 'Health Care': -0.28, 'Financials': -0.18, 'Consumer Discretionary': -0.2, 'Communication Services': 0.08, 'Industrials': -0.1, 'Consumer Staples': -0.05, 'Energy': 0.22, 'Utilities': -0.02, 'Real Estate': -0.22, 'Materials': -0.12}
{'Information Technology': 0.12, 'Health Care': -0.28, 'Financials': -0.18, 'Consumer Discretionary': -0.2, 'Communication Services': 0.08, 'Industrials': -0.1, 'Consumer Staples': -0.05, 'Energy': 0.22, 'Utilities': -0.02, 'Real Estate': -0.22, 'Materials': -0.12}
{'Information Technology': 0.12, 'Health Care': -0.28, 'Financials': -0.18, 'Consumer Discretionary': -0.2, 'Communication Services': 0.08, 'Industrials': -0.1, 'Consumer Staples': -0.05, 'Energy': 0.22, 'Utilities': -0.02, 'Real Estate': -0.22, 'Materials': -0.12}
{'Information Technology': 0.12, 'Health Care': -0.28, 'Financials': -0.18, 'Consumer Discretionary': -0.2, 'Communication Services': 0.08, 'Industrials': -0.1, 'Consumer Staples': -0.05, 'Energy': 0.22, 'Utilities': -0.02, 'Real Estate': -0.22, 'Materials': -0.12}
{'Information Technology': 0.12, 'Health Care': -0.28, 'Financials': -0.18, 'Consumer Discretionary': -0.2, 'Communication Services': 0.08, 'Industrials': -0.1, 'Consumer Staples': -0.05, 'Energy': 0.22, 'Utilities': -0.02, 'Real Estate': -0.22, 'Materials': -0.12}
{'Information Technology': 0.12, 'Health Care': -0.28, 'Financials': -0.18, 'Consumer Discretionary': -0.2, 'Communication Services': 0.08, 'Industrials': -0.1, 'Consumer Staples': -0.05, 'Energy': 0.22, 'Utilities': -0.02, 'Real Estate': -0.22, 'Materials': -0.12}
{'Information Technology': 0.12, 'Health Care': -0.28, 'Financials': -0.18, 'Consumer Discretionary': -0.2, 'Communication Services': 0.08, 'Industrials': -0.1, 'Consumer Staples': -0.05, 'Energy': 0.22, 'Utilities': -0.02, 'Real Estate': -0.22, 'Materials': -0.12}
{'Information Technology': 0.12, 'Health Care': -0.28, 'Financials': -0.18, 'Consumer Discretionary': -0.2, 'Communication Services': 0.08, 'Industrials': -0.1, 'Consumer Staples': -0.05, 'Energy': 0.22, 'Utilities': -0.02, 'Real Estate': -0.22, 'Materials': -0.12}
{'Information Technology': 0.12, 'Health Care': -0.28, 'Financials': -0.18, 'Consumer Discretionary': -0.2, 'Communication Services': 0.08, 'Industrials': -0.1, 'Consumer Staples': -0.05, 'Energy': 0.22, 'Utilities': -0.02, 'Real Estate': -0.22, 'Materials': -0.12}
{'Information Technology': 0.55, 'Health Care': 0.05, 'Financials': 0.1, 'Consumer Discretionary': 0.15, 'Communication Services': 0.2, 'Industrials': 0.2, 'Consumer Staples': -0.05, 'Energy': 0.0, 'Utilities': 0.05, 'Real Estate': -0.1, 'Materials': 0.15}
{'Information Technology': 0.55, 'Health Care': 0.05, 'Financials': 0.1, 'Consumer Discretionary': 0.15, 'Communication Services': 0.2, 'Industrials': 0.2, 'Consumer Staples': -0.05, 'Energy': 0.0, 'Utilities': 0.05, 'Real Estate': -0.1, 'Materials': 0.15}
{'Information Technology': 0.55, 'Health Care': 0.05, 'Financials': 0.1, 'Consumer Discretionary': 0.15, 'Communication Services': 0.2, 'Industrials': 0.2, 'Consumer Staples': -0.05, 'Energy': 0.0, 'Utilities': 0.05, 'Real Estate': -0.1, 'Materials': 0.15}
{'Information Technology': 0.55, 'Health Care': 0.05, 'Financials': 0.1, 'Consumer Discretionary': 0.15, 'Communication Services': 0.2, 'Industrials': 0.2, 'Consumer Staples': -0.05, 'Energy': 0.0, 'Utilities': 0.05, 'Real Estate': -0.1, 'Materials': 0.15}
{'Information Technology': 0.55, 'Health Care': 0.05, 'Financials': 0.1, 'Consumer Discretionary': 0.15, 'Communication Services': 0.2, 'Industrials': 0.2, 'Consumer Staples': -0.05, 'Energy': 0.0, 'Utilities': 0.05, 'Real Estate': -0.1, 'Materials': 0.15}
{'Information Technology': 0.55, 'Health Care': 0.05, 'Financials': 0.1, 'Consumer Discretionary': 0.15, 'Communication Services': 0.2, 'Industrials': 0.2, 'Consumer Staples': -0.05, 'Energy': 0.0, 'Utilities': 0.05, 'Real Estate': -0.1, 'Materials': 0.15}
{'Information Technology': 0.55, 'Health Care': 0.05, 'Financials': 0.1, 'Consumer Discretionary': 0.15, 'Communication Services': 0.2, 'Industrials': 0.2, 'Consumer Staples': -0.05, 'Energy': 0.0, 'Utilities': 0.05, 'Real Estate': -0.1, 'Materials': 0.15}
{'Information Technology': 0.55, 'Health Care': 0.05, 'Financials': 0.1, 'Consumer Discretionary': 0.15, 'Communication Services': 0.2, 'Industrials': 0.2, 'Consumer Staples': -0.05, 'Energy': 0.0, 'Utilities': 0.05, 'Real Estate': -0.1, 'Materials': 0.15}
{'Information Technology': 0.55, 'Health Care': 0.05, 'Financials': 0.1, 'Consumer Discretionary': 0.15, 'Communication Services': 0.2, 'Industrials': 0.2, 'Consumer Staples': -0.05, 'Energy': 0.0, 'Utilities': 0.05, 'Real Estate': -0.1, 'Materials': 0.15}
{'Information Technology': 0.55, 'Health Care': 0.05, 'Financials': 0.1, 'Consumer Discretionary': 0.15, 'Communication Services': 0.2, 'Industrials': 0.2, 'Consumer Staples': -0.05, 'Energy': 0.0, 'Utilities': 0.05, 'Real Estate': -0.1, 'Materials': 0.15}
{'Information Technology': 0.55, 'Health Care': 0.05, 'Financials': 0.1, 'Consumer Discretionary': 0.15, 'Communication Services': 0.2, 'Industrials': 0.2, 'Consumer Staples': -0.05, 'Energy': 0.0, 'Utilities': 0.05, 'Real Estate': -0.1, 'Materials': 0.15}
{'Information Technology': 0, 'Health Care': 0, 'Financials': 0, 'Consumer Discretionary': 0, 'Communication Services': 0, 'Industrials': 0, 'Consumer Staples': 0, 'Energy': 0, 'Utilities': 0, 'Real Estate': 0, 'Materials': 0}
{'Information Technology': 0, 'Health Care': 0, 'Financials': 0, 'Consumer Discretionary': 0, 'Communication Services': 0, 'Industrials': 0, 'Consumer Staples': 0, 'Energy': 0, 'Utilities': 0, 'Real Estate': 0, 'Materials': 0}
{'Information Technology': 0, 'Health Care': 0, 'Financials': 0, 'Consumer Discretionary': 0, 'Communication Services': 0, 'Industrials': 0, 'Consumer Staples': 0, 'Energy': 0, 'Utilities': 0, 'Real Estate': 0, 'Materials': 0}
{'Information Technology': 0, 'Health Care': 0, 'Financials': 0, 'Consumer Discretionary': 0, 'Communication Services': 0, 'Industrials': 0, 'Consumer Staples': 0, 'Energy': 0, 'Utilities': 0, 'Real Estate': 0, 'Materials': 0}
{'Information Technology': 0, 'Health Care': 0, 'Financials': 0, 'Consumer Discretionary': 0, 'Communication Services': 0, 'Industrials': 0, 'Consumer Staples': 0, 'Energy': 0, 'Utilities': 0, 'Real Estate': 0, 'Materials': 0}
{'Information Technology': 0, 'Health Care': 0, 'Financials': 0, 'Consumer Discretionary': 0, 'Communication Services': 0, 'Industrials': 0, 'Consumer Staples': 0, 'Energy': 0, 'Utilities': 0, 'Real Estate': 0, 'Materials': 0}
{'Information Technology': 0, 'Health Care': 0, 'Financials': 0, 'Consumer Discretionary': 0, 'Communication Services': 0, 'Industrials': 0, 'Consumer Staples': 0, 'Energy': 0, 'Utilities': 0, 'Real Estate': 0, 'Materials': 0}
{'Information Technology': 0, 'Health Care': 0, 'Financials': 0, 'Consumer Discretionary': 0, 'Communication Services': 0, 'Industrials': 0, 'Consumer Staples': 0, 'Energy': 0, 'Utilities': 0, 'Real Estate': 0, 'Materials': 0}
{'Information Technology': 0, 'Health Care': 0, 'Financials': 0, 'Consumer Discretionary': 0, 'Communication Services': 0, 'Industrials': 0, 'Consumer Staples': 0, 'Energy': 0, 'Utilities': 0, 'Real Estate': 0, 'Materials': 0}
{'Information Technology': 0, 'Health Care': 0, 'Financials': 0, 'Consumer Discretionary': 0, 'Communication Services': 0, 'Industrials': 0, 'Consumer Staples': 0, 'Energy': 0, 'Utilities': 0, 'Real Estate': 0, 'Materials': 0}
{'Information Technology': 0, 'Health Care': 0, 'Financials': 0, 'Consumer Discretionary': 0, 'Communication Services': 0, 'Industrials': 0, 'Consumer Staples': 0, 'Energy': 0, 'Utilities': 0, 'Real Estate': 0, 'Materials': 0}

In [41]:
df_flattened = pd.json_normalize(df['LLM Response'])

In [42]:
df_flattened

,Information Technology,Health Care,Financials,Consumer Discretionary,Communication Services,Industrials,Consumer Staples,Energy,Utilities,Real Estate,Materials
0,0.20,0.01,0.05,0.18,0.12,0.09,0.02,0.08,0.00,-0.03,0.04
1,0.74,0.08,0.12,0.68,0.82,0.41,0.05,0.18,-0.08,-0.35,0.20
2,0.61,0.05,0.08,0.12,0.22,0.74,0.02,0.78,0.57,0.18,0.33
3,0.30,-0.15,0.05,0.15,0.20,-0.10,-0.35,0.10,0.10,-0.25,-0.05
4,0.10,-0.10,0.45,0.15,0.05,0.00,0.10,0.20,0.05,0.00,-0.25
...,...,...,...,...,...,...,...,...,...,...,...
542,0.40,-0.20,0.85,0.45,0.10,0.35,-0.05,0.15,-0.10,0.20,0.25
543,0.20,0.08,0.12,0.10,0.15,0.05,0.05,-0.10,-0.05,-0.15,-0.05
544,0.25,0.05,0.05,0.15,0.30,0.10,0.00,-0.20,0.10,-0.05,0.00
545,0.45,0.02,0.06,0.18,0.32,0.04,-0.08,0.12,-0.05,-0.12,0.01
546,0.25,0.00,0.05,0.10,0.20,0.05,0.00,-0.05,0.00,-0.70,-0.05

In [43]:
df

           Date                                       LLM Response    1
0    11_05_2024  {'Information Technology': 0.2, 'Health Care':...  NaN
1    02_02_2024  {'Information Technology': 0.74, 'Health Care'...  NaN
2       MISSING  {'Information Technology': 0.61, 'Health Care'...  NaN
3    07_09_2024  {'Information Technology': 0.3, 'Health Care':...  NaN
4    10_16_2024  {'Information Technology': 0.1, 'Health Care':...  NaN
..          ...                                                ...  ...
542  11_06_2024  {'Information Technology': 0.4, 'Health Care':...  NaN
543  01_10_2025  {'Information Technology': 0.2, 'Health Care':...  NaN
544  02_07_2025  {'Information Technology': 0.25, 'Health Care'...  NaN
545  06_20_2024  {'Information Technology': 0.45, 'Health Care'...  NaN
546  02_07_2024  {'Information Technology': 0.25, 'Health Care'...  NaN

[547 rows x 3 columns]

In [45]:
df3 = df.join(df_flattened, how="inner")

In [48]:
df4 = df3.drop(["LLM Response", 1], axis=1)

In [49]:
df4

,Date,Information Technology,Health Care,Financials,Consumer Discretionary,Communication Services,Industrials,Consumer Staples,Energy,Utilities,Real Estate,Materials
0,11_05_2024,0.20,0.01,0.05,0.18,0.12,0.09,0.02,0.08,0.00,-0.03,0.04
1,02_02_2024,0.74,0.08,0.12,0.68,0.82,0.41,0.05,0.18,-0.08,-0.35,0.20
2,MISSING,0.61,0.05,0.08,0.12,0.22,0.74,0.02,0.78,0.57,0.18,0.33
3,07_09_2024,0.30,-0.15,0.05,0.15,0.20,-0.10,-0.35,0.10,0.10,-0.25,-0.05
4,10_16_2024,0.10,-0.10,0.45,0.15,0.05,0.00,0.10,0.20,0.05,0.00,-0.25
...,...,...,...,...,...,...,...,...,...,...,...,...
542,11_06_2024,0.40,-0.20,0.85,0.45,0.10,0.35,-0.05,0.15,-0.10,0.20,0.25
543,01_10_2025,0.20,0.08,0.12,0.10,0.15,0.05,0.05,-0.10,-0.05,-0.15,-0.05
544,02_07_2025,0.25,0.05,0.05,0.15,0.30,0.10,0.00,-0.20,0.10,-0.05,0.00
545,06_20_2024,0.45,0.02,0.06,0.18,0.32,0.04,-0.08,0.12,-0.05,-0.12,0.01
546,02_07_2024,0.25,0.00,0.05,0.10,0.20,0.05,0.00,-0.05,0.00,-0.70,-0.05

In [50]:
df4.to_csv("./sentiment_analysis/cleaned_Bloomberg_Transcript_Results.csv", index=False)